from napp_pdi.utils import normalize_str
from pathlib import Path

class Color():
	def __init__(self):
		self.color_map = [
			{'name': 'Água', 'hex': '#00FFFF', 'keywords': self.__generate_keywords('Água')}, 
			{'name': 'Azul Turquesa', 'hex': '#00CCEE', 'keywords': self.__generate_keywords('Azul Turquesa')}, 
			{'name': 'Azul Turquesa Brilhante', 'hex': '#00DDFF', 'keywords': self.__generate_keywords('Azul Turquesa Brilhante')}, 
			{'name': 'Azul Brasilis', 'hex': '#00BDCE', 'keywords': self.__generate_keywords('Azul Brasilis')}, 
			{'name': 'Azul Brasilis Brilhante', 'hex': '#09ACDB', 'keywords': self.__generate_keywords('Azul Brasilis Brilhante')}, 
			{'name': 'Água-marinha', 'hex': '#7FFFD4', 'keywords': self.__generate_keywords('Água-marinha')}, 
			{'name': 'Água-marinha média', 'hex': '#66CDAA', 'keywords': self.__generate_keywords('Água-marinha média')}, 
			{'name': 'Azul-Celeste Pernambucano', 'hex': '#00A4CD', 'keywords': self.__generate_keywords('Azul-Celeste Pernambucano')}, 
			{'name': 'Alizarina', 'hex': '#E32636', 'keywords': self.__generate_keywords('Alizarina')}, 
			{'name': 'Amarelo', 'hex': '#FFFF00', 'keywords': self.__generate_keywords('Amarelo')}, 
			{'name': 'Amarelo-Brasilis', 'hex': '#ECDB00', 'keywords': self.__generate_keywords('Amarelo-Brasilis')}, 
			{'name': 'Amarelo-Creme', 'hex': '#ECD690', 'keywords': self.__generate_keywords('Amarelo-Creme')}, 
			{'name': 'Amarelo claro', 'hex': '#FFFFE0', 'keywords': self.__generate_keywords('Amarelo claro')}, 
			{'name': 'Amarelo escuro', 'hex': '#F2B73F', 'keywords': self.__generate_keywords('Amarelo escuro')}, 
			{'name': 'Amarelo esverdeado', 'hex': '#ADFF2F', 'keywords': self.__generate_keywords('Amarelo esverdeado')}, 
			{'name': 'Amarelo ouro claro', 'hex': '#FAFAD2', 'keywords': self.__generate_keywords('Amarelo ouro claro')}, 
			{'name': 'Amarelo queimado', 'hex': '#EEAD2D', 'keywords': self.__generate_keywords('Amarelo queimado')}, 
			{'name': 'Âmbar', 'hex': '#FFBF00', 'keywords': self.__generate_keywords('Âmbar')}, 
			{'name': 'Ameixa', 'hex': '#DDA0DD', 'keywords': self.__generate_keywords('Ameixa')}, 
			{'name': 'Ametista', 'hex': '#9966CC', 'keywords': self.__generate_keywords('Ametista')}, 
			{'name': 'Amêndoa', 'hex': '#FFEBCD', 'keywords': self.__generate_keywords('Amêndoa')}, 
			{'name': 'Aspargo', 'hex': '#7BA05B', 'keywords': self.__generate_keywords('Aspargo')}, 
			{'name': 'Azul', 'hex': '#0000FF', 'keywords': self.__generate_keywords('Azul')}, 
			{'name': 'Azul alice', 'hex': '#F0F8FF', 'keywords': self.__generate_keywords('Azul alice')}, 
			{'name': 'Azul ardósia', 'hex': '#6A5ACD', 'keywords': self.__generate_keywords('Azul ardósia')}, 
			{'name': 'Azul ardósia claro', 'hex': '#8470FF', 'keywords': self.__generate_keywords('Azul ardósia claro')}, 
			{'name': 'Azul ardósia escuro', 'hex': '#483D8B', 'keywords': self.__generate_keywords('Azul ardósia escuro')}, 
			{'name': 'Azul ardósia médio', 'hex': '#7B68EE', 'keywords': self.__generate_keywords('Azul ardósia médio')}, 
			{'name': 'Azul areado', 'hex': '#B8CAD4', 'keywords': self.__generate_keywords('Azul areado')}, 
			{'name': 'Azul aço', 'hex': '#4682B4', 'keywords': self.__generate_keywords('Azul aço')}, 
			{'name': 'Azul aço claro', 'hex': '#B0C4DE', 'keywords': self.__generate_keywords('Azul aço claro')}, 
			{'name': 'Azul cadete', 'hex': '#5F9EA0', 'keywords': self.__generate_keywords('Azul cadete')}, 
			{'name': 'Azul camarada', 'hex': '#054F77', 'keywords': self.__generate_keywords('Azul camarada')}, 
			{'name': 'Azul celeste', 'hex': '#F0FFFF', 'keywords': self.__generate_keywords('Azul celeste')}, 
			{'name': 'Azul celeste brilhante', 'hex': '#007FFF', 'keywords': self.__generate_keywords('Azul celeste brilhante')}, 
			{'name': 'Azul claro', 'hex': '#ADD8E6', 'keywords': self.__generate_keywords('Azul claro')}, 
			{'name': 'Azul cobalto', 'hex': '#0047AB', 'keywords': self.__generate_keywords('Azul cobalto')}, 
			{'name': 'Azul céu', 'hex': '#87CEEB', 'keywords': self.__generate_keywords('Azul céu')}, 
			{'name': 'Azul céu claro', 'hex': '#87CEFA', 'keywords': self.__generate_keywords('Azul céu claro')}, 
			{'name': 'Azul céu profundo', 'hex': '#00BFFF', 'keywords': self.__generate_keywords('Azul céu profundo')}, 
			{'name': 'Azul escuro', 'hex': '#00008B', 'keywords': self.__generate_keywords('Azul escuro')}, 
			{'name': 'Azul flor de milho', 'hex': '#6495ED', 'keywords': self.__generate_keywords('Azul flor de milho')}, 
			{'name': 'Azul força aérea', 'hex': '#5D8AA8', 'keywords': self.__generate_keywords('Azul força aérea')}, 
			{'name': 'Azul furtivo', 'hex': '#1E90FF', 'keywords': self.__generate_keywords('Azul furtivo')}, 
			{'name': 'Azul manteiga', 'hex': '#a6aa3e', 'keywords': self.__generate_keywords('Azul manteiga')}, 
			{'name': 'Azul marinho', 'hex': '#120A8F', 'keywords': self.__generate_keywords('Azul marinho')}, 
			{'name': 'Azul meia-noite', 'hex': '#191970', 'keywords': self.__generate_keywords('Azul meia-noite')}, 
			{'name': 'Azul médio', 'hex': '#0000CD', 'keywords': self.__generate_keywords('Azul médio')}, 
			{'name': 'Azul petróleo', 'hex': '#084D6E', 'keywords': self.__generate_keywords('Azul petróleo')}, 
			{'name': 'Azul pólvora', 'hex': '#B0E0E6', 'keywords': self.__generate_keywords('Azul pólvora')}, 
			{'name': 'Azul taparuere', 'hex': '#248EFF', 'keywords': self.__generate_keywords('Azul taparuere')}, 
			{'name': 'Azul real', 'hex': '#0000DD', 'keywords': self.__generate_keywords('Azul real')}, 
			{'name': 'Azul violeta', 'hex': '#8A2BE2', 'keywords': self.__generate_keywords('Azul violeta')}, 
			{'name': 'Açafrão', 'hex': '#F4C430', 'keywords': self.__generate_keywords('Açafrão')}, 
			{'name': 'Bege', 'hex': '#F5F5DC', 'keywords': self.__generate_keywords('Bege')}, 
			{'name': 'Bordô', 'hex': '#800000', 'keywords': self.__generate_keywords('Bordô')}, 
			{'name': 'Borgonha', 'hex': '#900020', 'keywords': self.__generate_keywords('Borgonha')}, 
			{'name': 'Branco', 'hex': '#FFFFFF', 'keywords': self.__generate_keywords('Branco')}, 
			{'name': 'Branco antigo', 'hex': '#FAEBD7', 'keywords': self.__generate_keywords('Branco antigo')}, 
			{'name': 'Branco fantasma', 'hex': '#F8F8FF', 'keywords': self.__generate_keywords('Branco fantasma')}, 
			{'name': 'Branco floral', 'hex': '#FFFAF0', 'keywords': self.__generate_keywords('Branco floral')}, 
			{'name': 'Branco fumaça', 'hex': '#F5F5F5', 'keywords': self.__generate_keywords('Branco fumaça')}, 
			{'name': 'Branco navajo', 'hex': '#FFDEAD', 'keywords': self.__generate_keywords('Branco navajo')}, 
			{'name': 'Brasil', 'hex': '#A7F432', 'keywords': self.__generate_keywords('Brasil')}, 
			{'name': 'Bronze', 'hex': '#CD7F32', 'keywords': self.__generate_keywords('Bronze')}, 
			{'name': 'Caramelo', 'hex': '#8B5742', 'keywords': self.__generate_keywords('Caramelo')}, 
			{'name': 'Caqui', 'hex': '#F0E68C', 'keywords': self.__generate_keywords('Caqui')}, 
			{'name': 'Cardo', 'hex': '#D8BFD8', 'keywords': self.__generate_keywords('Cardo')}, 
			{'name': 'Carmesim', 'hex': '#DC143C', 'keywords': self.__generate_keywords('Carmesim')}, 
			{'name': 'Carmim', 'hex': '#712F26', 'keywords': self.__generate_keywords('Carmim')}, 
			{'name': 'Carmim Clássico', 'hex': '#992244', 'keywords': self.__generate_keywords('Carmim Clássico')}, 
			{'name': 'Carmim carnáceo', 'hex': '#960018', 'keywords': self.__generate_keywords('Carmim carnáceo')}, 
			{'name': 'Castanho avermelhado', 'hex': '#8B0000', 'keywords': self.__generate_keywords('Castanho avermelhado')}, 
			{'name': 'Castanho claro', 'hex': '#D2B48C', 'keywords': self.__generate_keywords('Castanho claro')}, 
			{'name': 'Cenoura', 'hex': '#ED9121', 'keywords': self.__generate_keywords('Cenoura')}, 
			{'name': 'Cereja', 'hex': '#DE3163', 'keywords': self.__generate_keywords('Cereja')}, 
			{'name': 'Cereja Hollywood', 'hex': '#F400A1', 'keywords': self.__generate_keywords('Cereja Hollywood')}, 
			{'name': 'Chocolate', 'hex': '#D2691E', 'keywords': self.__generate_keywords('Chocolate')}, 
			{'name': 'Ciano', 'hex': '#00FFFF', 'keywords': self.__generate_keywords('Ciano')}, 
			{'name': 'Ciano claro', 'hex': '#E0FFFF', 'keywords': self.__generate_keywords('Ciano claro')}, 
			{'name': 'Ciano escuro', 'hex': '#008B8B', 'keywords': self.__generate_keywords('Ciano escuro')}, 
			{'name': 'Cinza', 'hex': '#808080', 'keywords': self.__generate_keywords('Cinza')}, 
			{'name': 'Cinza ardósia', 'hex': '#708090', 'keywords': self.__generate_keywords('Cinza ardósia')}, 
			{'name': 'Cinza ardósia claro', 'hex': '#778899', 'keywords': self.__generate_keywords('Cinza ardósia claro')}, 
			{'name': 'Cinza ardósia escuro', 'hex': '#2F4F4F', 'keywords': self.__generate_keywords('Cinza ardósia escuro')}, 
			{'name': 'Cinza claro', 'hex': '#D3D3D3', 'keywords': self.__generate_keywords('Cinza claro')}, 
			{'name': 'Cinza escuro', 'hex': '#A9A9A9', 'keywords': self.__generate_keywords('Cinza escuro')}, 
			{'name': 'Cinza fosco', 'hex': '#696969', 'keywords': self.__generate_keywords('Cinza fosco')}, 
			{'name': 'Cinza médio', 'hex': '#DCDCDC', 'keywords': self.__generate_keywords('Cinza médio')}, 
			{'name': 'Cobre', 'hex': '#B87333', 'keywords': self.__generate_keywords('Cobre')}, 
			{'name': 'Concha', 'hex': '#FFF5EE', 'keywords': self.__generate_keywords('Concha')}, 
			{'name': 'Coral', 'hex': '#FF7F50', 'keywords': self.__generate_keywords('Coral')}, 
			{'name': 'Coral claro', 'hex': '#F08080', 'keywords': self.__generate_keywords('Coral claro')}, 
			{'name': 'Couro', 'hex': '#F0DC82', 'keywords': self.__generate_keywords('Couro')}, 
			{'name': 'Creme', 'hex': '#FFFDD0', 'keywords': self.__generate_keywords('Creme')}, 
			{'name': 'Creme de marisco', 'hex': '#FFE4C4', 'keywords': self.__generate_keywords('Creme de marisco')}, 
			{'name': 'Creme de menta', 'hex': '#F5FFFA', 'keywords': self.__generate_keywords('Creme de menta')}, 
			{'name': 'Caqui escuro', 'hex': '#BDB76B', 'keywords': self.__generate_keywords('Caqui escuro')}, 
			{'name': 'Dainise', 'hex': '#778899', 'keywords': self.__generate_keywords('Dainise')}, 
			{'name': 'Dourado', 'hex': '#DAA520', 'keywords': self.__generate_keywords('Dourado')}, 
			{'name': 'Dourado escuro', 'hex': '#B8860B', 'keywords': self.__generate_keywords('Dourado escuro')}, 
			{'name': 'Dourado pálido', 'hex': '#EEE8AA', 'keywords': self.__generate_keywords('Dourado pálido')}, 
			{'name': 'Ébano', 'hex': '#555D50', 'keywords': self.__generate_keywords('Ébano')}, 
			{'name': 'Eminência', 'hex': '#6C3082', 'keywords': self.__generate_keywords('Eminência')}, 
			{'name': 'Escarlate', 'hex': '#FF2400', 'keywords': self.__generate_keywords('Escarlate')}, 
			{'name': 'Esmeralda', 'hex': '#50C878', 'keywords': self.__generate_keywords('Esmeralda')}, 
			{'name': 'Eucalipto', 'hex': '#44D7A8', 'keywords': self.__generate_keywords('Eucalipto')}, 
			{'name': 'Fandango', 'hex': '#B53389', 'keywords': self.__generate_keywords('Fandango')}, 
			{'name': 'Feldspato', 'hex': '#FDD5B1', 'keywords': self.__generate_keywords('Feldspato')}, 
			{'name': 'Ferrugem', 'hex': '#B7410E', 'keywords': self.__generate_keywords('Ferrugem')}, 
			{'name': 'Flerte', 'hex': '#A2006D', 'keywords': self.__generate_keywords('Flerte')}, 
			{'name': 'Fuligem', 'hex': '#3D2B1F', 'keywords': self.__generate_keywords('Fuligem')}, 
			{'name': 'Fúchsia', 'hex': '#FF00FF', 'keywords': self.__generate_keywords('Fúchsia')}, 
			{'name': 'Grená', 'hex': '#831D1C', 'keywords': self.__generate_keywords('Grená')}, 
			{'name': 'Gainsboro', 'hex': '#DCDCDC', 'keywords': self.__generate_keywords('Gainsboro')}, 
			{'name': 'Glitter', 'hex': '#E6E8FA', 'keywords': self.__generate_keywords('Glitter')}, 
			{'name': 'Herbal', 'hex': '#2E8B57', 'keywords': self.__generate_keywords('Herbal')}, 
			{'name': 'Heliotrópio', 'hex': '#DF73FF', 'keywords': self.__generate_keywords('Heliotrópio')}, 
			{'name': 'Índigo', 'hex': '#4B0082', 'keywords': self.__generate_keywords('Índigo')}, 
			{'name': 'Independência', 'hex': '#4C516D', 'keywords': self.__generate_keywords('Independência')}, 
			{'name': 'Iris', 'hex': '#5A4FCF', 'keywords': self.__generate_keywords('Iris')}, 
			{'name': 'Jade', 'hex': '#00A86B', 'keywords': self.__generate_keywords('Jade')}, 
			{'name': 'Jambo', 'hex': '#FF4500', 'keywords': self.__generate_keywords('Jambo')}, 
			{'name': 'Jasmine', 'hex': '#F8DE7E', 'keywords': self.__generate_keywords('Jasmine')}, 
			{'name': 'Kiwi', 'hex': '#8EE53F', 'keywords': self.__generate_keywords('Kiwi')}, 
			{'name': 'Kobi', 'hex': '#E79FC4', 'keywords': self.__generate_keywords('Kobi')}, 
			{'name': 'Kobicha', 'hex': '#6B4423', 'keywords': self.__generate_keywords('Kobicha')}, 
			{'name': 'Laranja', 'hex': '#FFA500', 'keywords': self.__generate_keywords('Laranja')}, 
			{'name': 'Laranja escuro', 'hex': '#FF8C00', 'keywords': self.__generate_keywords('Laranja escuro')}, 
			{'name': 'Laranja claro', 'hex': '#FFB84D', 'keywords': self.__generate_keywords('Laranja claro')}, 
			{'name': 'Lavanda', 'hex': '#E6E6FA', 'keywords': self.__generate_keywords('Lavanda')}, 
			{'name': 'Lavanda avermelhada', 'hex': '#FFF0F5', 'keywords': self.__generate_keywords('Lavanda avermelhada')}, 
			{'name': 'Lilás', 'hex': '#C8A2C8', 'keywords': self.__generate_keywords('Lilás')}, 
			{'name': 'Lima', 'hex': '#FDE910', 'keywords': self.__generate_keywords('Lima')}, 
			{'name': 'Linho', 'hex': '#FAF0E6', 'keywords': self.__generate_keywords('Linho')}, 
			{'name': 'Madeira', 'hex': '#DEB887', 'keywords': self.__generate_keywords('Madeira')}, 
			{'name': 'Magenta', 'hex': '#FF00FF', 'keywords': self.__generate_keywords('Magenta')}, 
			{'name': 'Magenta escuro', 'hex': '#8B008B', 'keywords': self.__generate_keywords('Magenta escuro')}, 
			{'name': 'Malva', 'hex': '#E0B0FF', 'keywords': self.__generate_keywords('Malva')}, 
			{'name': 'Mamão batido', 'hex': '#FFEFD5', 'keywords': self.__generate_keywords('Mamão batido')}, 
			{'name': 'Maná', 'hex': '#F0FFF0', 'keywords': self.__generate_keywords('Maná')}, 
			{'name': 'Marfim', 'hex': '#FFFFF0', 'keywords': self.__generate_keywords('Marfim')}, 
			{'name': 'Marrom', 'hex': '#964b00', 'keywords': self.__generate_keywords('Marrom')}, 
			{'name': 'Marrom amarelado', 'hex': '#F4A460', 'keywords': self.__generate_keywords('Marrom amarelado')}, 
			{'name': 'Marrom claro', 'hex': '#A52A2A', 'keywords': self.__generate_keywords('Marrom claro')}, 
			{'name': 'Marrom rosado', 'hex': '#BC8F8F', 'keywords': self.__generate_keywords('Marrom rosado')}, 
			{'name': 'Marrom sela', 'hex': '#8B4513', 'keywords': self.__generate_keywords('Marrom sela')}, 
			{'name': 'Milho', 'hex': '#FBEC5D', 'keywords': self.__generate_keywords('Milho')}, 
			{'name': 'Milho Claro', 'hex': '#FFF8DC', 'keywords': self.__generate_keywords('Milho Claro')}, 
			{'name': 'Mocassim', 'hex': '#FFE4B5', 'keywords': self.__generate_keywords('Mocassim')}, 
			{'name': 'Mostarda', 'hex': '#FFDB58', 'keywords': self.__generate_keywords('Mostarda')}, 
			{'name': 'Naval', 'hex': '#000080', 'keywords': self.__generate_keywords('Naval')}, 
			{'name': 'Neve', 'hex': '#FFFAFA', 'keywords': self.__generate_keywords('Neve')}, 
			{'name': 'Nyanza', 'hex': '#E9FFDB', 'keywords': self.__generate_keywords('Nyanza')}, 
			{'name': 'Ocre', 'hex': '#CC7722', 'keywords': self.__generate_keywords('Ocre')}, 
			{'name': 'Oliva', 'hex': '#808000', 'keywords': self.__generate_keywords('Oliva')}, 
			{'name': 'Oliva escura', 'hex': '#556B2F', 'keywords': self.__generate_keywords('Oliva escura')}, 
			{'name': 'Oliva parda', 'hex': '#6B8E23', 'keywords': self.__generate_keywords('Oliva parda')}, 
			{'name': 'Orquídea', 'hex': '#DA70D6', 'keywords': self.__generate_keywords('Orquídea')}, 
			{'name': 'Orquídea escura', 'hex': '#9932CC', 'keywords': self.__generate_keywords('Orquídea escura')}, 
			{'name': 'Orquídea média', 'hex': '#BA55D3', 'keywords': self.__generate_keywords('Orquídea média')}, 
			{'name': 'Ouro', 'hex': '#FFD700', 'keywords': self.__generate_keywords('Ouro')}, 
			{'name': 'Pardo', 'hex': '#CD853F', 'keywords': self.__generate_keywords('Pardo')}, 
			{'name': 'Pardo escuro', 'hex': '#CC6600', 'keywords': self.__generate_keywords('Pardo escuro')}, 
			{'name': 'Prata', 'hex': '#C0C0C0', 'keywords': self.__generate_keywords('Prata')}, 
			{'name': 'Preto', 'hex': '#000000', 'keywords': self.__generate_keywords('Preto')}, 
			{'name': 'Pêssego', 'hex': '#FFDAB9', 'keywords': self.__generate_keywords('Pêssego')}, 
			{'name': 'Púrpura', 'hex': '#800080', 'keywords': self.__generate_keywords('Púrpura')}, 
			{'name': 'Púrpura média', 'hex': '#9370DB', 'keywords': self.__generate_keywords('Púrpura média')}, 
			{'name': 'Quantum', 'hex': '#111111', 'keywords': self.__generate_keywords('Quantum')}, 
			{'name': 'Quartz', 'hex': '#51484F', 'keywords': self.__generate_keywords('Quartz')}, 
			{'name': 'Renda antiga', 'hex': '#FDF5E6', 'keywords': self.__generate_keywords('Renda antiga')}, 
			{'name': 'Rosa', 'hex': '#FFCBDB', 'keywords': self.__generate_keywords('Rosa')}, 
			{'name': 'Rosa brilhante', 'hex': '#FF007F', 'keywords': self.__generate_keywords('Rosa brilhante')}, 
			{'name': 'Rosa Choque', 'hex': '#FC0FC0', 'keywords': self.__generate_keywords('Rosa Choque')}, 
			{'name': 'Rosa amoroso', 'hex': '#CD69CD', 'keywords': self.__generate_keywords('Rosa amoroso')}, 
			{'name': 'Rosa claro', 'hex': '#FFB6C1', 'keywords': self.__generate_keywords('Rosa claro')}, 
			{'name': 'Rosa Danação', 'hex': '#DA69A1', 'keywords': self.__generate_keywords('Rosa Danação')}, 
			{'name': 'Rosa embaçado', 'hex': '#FFE4E1', 'keywords': self.__generate_keywords('Rosa embaçado')}, 
			{'name': 'Rosa forte', 'hex': '#FF69B4', 'keywords': self.__generate_keywords('Rosa forte')}, 
			{'name': 'Rosa profundo', 'hex': '#FF1493', 'keywords': self.__generate_keywords('Rosa profundo')}, 
			{'name': 'Roxo', 'hex': '#993399', 'keywords': self.__generate_keywords('Roxo')}, 
			{'name': 'Roxo–Brasilis', 'hex': '#8A008A', 'keywords': self.__generate_keywords('Roxo–Brasilis')}, 
			{'name': 'Rútilo', 'hex': '#6D351A', 'keywords': self.__generate_keywords('Rútilo')}, 
			{'name': 'Salmão', 'hex': '#FA7F72', 'keywords': self.__generate_keywords('Salmão')}, 
			{'name': 'Salmão claro', 'hex': '#FFA07A', 'keywords': self.__generate_keywords('Salmão claro')}, 
			{'name': 'Salmão escuro', 'hex': '#E9967A', 'keywords': self.__generate_keywords('Salmão escuro')}, 
			{'name': 'Siena', 'hex': '#FF8247', 'keywords': self.__generate_keywords('Siena')}, 
			{'name': 'Sépia', 'hex': '#705714', 'keywords': self.__generate_keywords('Sépia')}, 
			{'name': 'Tangerina', 'hex': '#F28500', 'keywords': self.__generate_keywords('Tangerina')}, 
			{'name': 'Terracota', 'hex': '#E2725B', 'keywords': self.__generate_keywords('Terracota')}, 
			{'name': 'Tijolo refratário', 'hex': '#B22222', 'keywords': self.__generate_keywords('Tijolo refratário')}, 
			{'name': 'Tomate', 'hex': '#FF6347', 'keywords': self.__generate_keywords('Tomate')}, 
			{'name': 'Trigo', 'hex': '#F5DEB3', 'keywords': self.__generate_keywords('Trigo')}, 
			{'name': 'Triássico', 'hex': '#FF2401', 'keywords': self.__generate_keywords('Triássico')}, 
			{'name': 'Turquesa', 'hex': '#40E0D0', 'keywords': self.__generate_keywords('Turquesa')}, 
			{'name': 'Turquesa escura', 'hex': '#00CED1', 'keywords': self.__generate_keywords('Turquesa escura')}, 
			{'name': 'Turquesa média', 'hex': '#48D1CC', 'keywords': self.__generate_keywords('Turquesa média')}, 
			{'name': 'Turquesa pálida', 'hex': '#AFEEEE', 'keywords': self.__generate_keywords('Turquesa pálida')}, 
			{'name': 'Tangerina', 'hex': '#F28500', 'keywords': self.__generate_keywords('Tangerina')}, 
			{'name': 'Terracota', 'hex': '#E2725B', 'keywords': self.__generate_keywords('Terracota')}, 
			{'name': 'Tijolo refratário', 'hex': '#B22222', 'keywords': self.__generate_keywords('Tijolo refratário')}, 
			{'name': 'Tomate', 'hex': '#FF6347', 'keywords': self.__generate_keywords('Tomate')}, 
			{'name': 'Trigo', 'hex': '#F5DEB3', 'keywords': self.__generate_keywords('Trigo')}, 
			{'name': 'Triássico', 'hex': '#FF2401', 'keywords': self.__generate_keywords('Triássico')}, 
			{'name': 'Turquesa', 'hex': '#40E0D0', 'keywords': self.__generate_keywords('Turquesa')}, 
			{'name': 'Turquesa escura', 'hex': '#00CED1', 'keywords': self.__generate_keywords('Turquesa escura')}, 
			{'name': 'Turquesa média', 'hex': '#48D1CC', 'keywords': self.__generate_keywords('Turquesa média')}, 
			{'name': 'Turquesa pálida', 'hex': '#AFEEEE', 'keywords': self.__generate_keywords('Turquesa pálida')}, 
			{'name': 'Verde', 'hex': '#008000', 'keywords': self.__generate_keywords('Verde')}, 
			{'name': 'Verde espectro', 'hex': '#00FF00', 'keywords': self.__generate_keywords('Verde espectro')}, 
			{'name': 'Verde amarelado', 'hex': '#9ACD32', 'keywords': self.__generate_keywords('Verde amarelado')}, 
			{'name': 'Verde claro', 'hex': '#90EE90', 'keywords': self.__generate_keywords('Verde claro')}, 
			{'name': 'Verde escuro', 'hex': '#006400', 'keywords': self.__generate_keywords('Verde escuro')}, 
			{'name': 'Verde floresta', 'hex': '#228B22', 'keywords': self.__generate_keywords('Verde floresta')}, 
			{'name': 'Verde fluorescente', 'hex': '#CCFF33', 'keywords': self.__generate_keywords('Verde fluorescente')}, 
			{'name': 'Verde lima', 'hex': '#32CD32', 'keywords': self.__generate_keywords('Verde lima')}, 
			{'name': 'Verde grama', 'hex': '#7CFC00', 'keywords': self.__generate_keywords('Verde grama')}, 
			{'name': 'Verde mar claro', 'hex': '#20B2AA', 'keywords': self.__generate_keywords('Verde mar claro')}, 
			{'name': 'Verde mar escuro', 'hex': '#8FBC8F', 'keywords': self.__generate_keywords('Verde mar escuro')}, 
			{'name': 'Verde mar médio', 'hex': '#3CB371', 'keywords': self.__generate_keywords('Verde mar médio')}, 
			{'name': 'Verde militar', 'hex': '#78866B', 'keywords': self.__generate_keywords('Verde militar')}, 
			{'name': 'Verde Paris', 'hex': '#7FFF00', 'keywords': self.__generate_keywords('Verde Paris')}, 
			{'name': 'Verde primavera', 'hex': '#00FF7F', 'keywords': self.__generate_keywords('Verde primavera')}, 
			{'name': 'Verde primavera médio', 'hex': '#00FA9A', 'keywords': self.__generate_keywords('Verde primavera médio')}, 
			{'name': 'Verde pálido', 'hex': '#98FB98', 'keywords': self.__generate_keywords('Verde pálido')}, 
			{'name': 'Verde-azulado', 'hex': '#008080', 'keywords': self.__generate_keywords('Verde-azulado')}, 
			{'name': 'Vermelho', 'hex': '#FF0000', 'keywords': self.__generate_keywords('Vermelho')}, 
			{'name': 'Vermelho enegrecido', 'hex': '#550000', 'keywords': self.__generate_keywords('Vermelho enegrecido')}, 
			{'name': 'Vermelho escuro', 'hex': '#8B0000', 'keywords': self.__generate_keywords('Vermelho escuro')}, 
			{'name': 'Vermelho indiano', 'hex': '#CD5C5C', 'keywords': self.__generate_keywords('Vermelho indiano')}, 
			{'name': 'Vermelho violeta', 'hex': '#D02090', 'keywords': self.__generate_keywords('Vermelho violeta')}, 
			{'name': 'Vermelho violeta médio', 'hex': '#C71585', 'keywords': self.__generate_keywords('Vermelho violeta médio')}, 
			{'name': 'Vermelho violeta pálido', 'hex': '#DB7093', 'keywords': self.__generate_keywords('Vermelho violeta pálido')}, 
			{'name': 'Violeta', 'hex': '#EE82EE', 'keywords': self.__generate_keywords('Violeta')}, 
			{'name': 'Violeta escuro', 'hex': '#9400D3', 'keywords': self.__generate_keywords('Violeta escuro')}, 
			{'name': 'Violeta claro', 'hex': '#F8CBF8', 'keywords': self.__generate_keywords('Violeta claro')}, 
			{'name': 'Wageningen Verde', 'hex': '#34B233', 'keywords': self.__generate_keywords('Wageningen Verde')}, 
			{'name': 'Wenge', 'hex': '#645452', 'keywords': self.__generate_keywords('Wenge')}, 
			{'name': 'Wisteria', 'hex': '#C9A0DC', 'keywords': self.__generate_keywords('Wisteria')}, 
			{'name': 'Xanadu', 'hex': '#738678', 'keywords': self.__generate_keywords('Xanadu')}, 
			{'name': 'Yale Blue', 'hex': '#0F4D92', 'keywords': self.__generate_keywords('Yale Blue')}, 
			{'name': 'Yellow', 'hex': '#FFFF00', 'keywords': self.__generate_keywords('Yellow')}, 
			{'name': 'Yellow-green', 'hex': '#9ACD32', 'keywords': self.__generate_keywords('Yellow-green')}, 
			{'name': 'Zaffre', 'hex': '#0014A8', 'keywords': self.__generate_keywords('Zaffre')}, 
			{'name': 'Zomp', 'hex': '#39A78E', 'keywords': self.__generate_keywords('Zomp')}, 
			{'name': 'Zinco', 'hex': '#E2DDF0', 'keywords': self.__generate_keywords('Zinco')}
		]

	def __generate_keywords(self, color_name):
		keywords = []

		keywords.append(normalize_str(color_name))
		keywords.append(normalize_str(color_name).replace(' ', ''))
		keywords.append(normalize_str(color_name, translate_spaces_to="_"))
		keywords.append(normalize_str(color_name, translate_spaces_to="-"))
		keywords.append(normalize_str(color_name, translate_spaces_to="."))
		keywords.append(normalize_str(color_name).lower())
		keywords.append(normalize_str(color_name).upper())

		keywords.append(color_name.replace(' ', ''))
		keywords.append(color_name.replace(' ', '_'))
		keywords.append(color_name.replace(' ', '-'))
		keywords.append(color_name.replace(' ', '.'))
		keywords.append(color_name.lower())
		keywords.append(color_name.upper())
		return keywords

	def get_color(self, color):
		color_hex = None
		for color_m in self.color_map:
			if color in color_m['keywords']:
				color_hex = color_m["hex"]

		if not color_hex:
			for color_m in self.color_map:
				for key in color_m['keywords']:
					if color in key:
						color_hex = color_m['hex']

		if not color_hex:
			for color_m in self.color_map:
				for key in color_m['keywords']:
					if normalize_str(color) in key:
						color_hex = color_m['hex']			
		
		if not color_hex:
			for color_m in self.color_map:
				if normalize_str(color) in color_m['keywords']:
					color_hex = color_m["hex"]
		if not color_hex:
			color_hex = "#000000"

		return color_hex


